// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pas.Forms.Website.Data;

namespace Pas.Forms.Website.Migrations
{
    [DbContext(typeof(FormsDbContext))]
    [Migration("20201114090930_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Pas.Forms.Website.Data.Db", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dbs");
                });

            modelBuilder.Entity("Pas.Forms.Website.Data.DbField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DbTableId")
                        .HasColumnType("int");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForeignTable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForeignTableKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InsertIgnore")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForeignKey")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UpdateIgnore")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DbTableId");

                    b.ToTable("DbFields");
                });

            modelBuilder.Entity("Pas.Forms.Website.Data.DbTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DbConnectionId")
                        .HasColumnType("int");

                    b.Property<int?>("DbId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DbId");

                    b.ToTable("DbTables");
                });

            modelBuilder.Entity("Pas.Forms.Website.Data.DbField", b =>
                {
                    b.HasOne("Pas.Forms.Website.Data.DbTable", "DbTable")
                        .WithMany("Fields")
                        .HasForeignKey("DbTableId");

                    b.Navigation("DbTable");
                });

            modelBuilder.Entity("Pas.Forms.Website.Data.DbTable", b =>
                {
                    b.HasOne("Pas.Forms.Website.Data.Db", null)
                        .WithMany("Tables")
                        .HasForeignKey("DbId");
                });

            modelBuilder.Entity("Pas.Forms.Website.Data.Db", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("Pas.Forms.Website.Data.DbTable", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
